project:
  type: website
  output-dir: docs

# Meta
description-meta: "Quarto Academic Website Template adapted from Dr. Gang He"
author-meta: "Dr. Gang He"

website:
  title: "Erin Marie San Valentin"
  image: "https://quarto.org/quarto.png"
  description: "Quarto Academic Website Template adapted from Dr. Gang He"
 
  navbar:
    background: light

    left:
      - text: About
        menu: 
          - text: Download my CV
            href: files/cv_20251002.pdf
          - text: Contact 
            href: contact.qmd       
      - text: Research
        menu:
          - text: Featured Publications
            href: featured-papers.qmd
          - text: Research Interests
            href: interests.qmd
          - text: Full Publication List
            href: publications.qmd
      - text: Beyond Research
        href: beyond.qmd

  
  page-navigation: true
  
  page-footer: 
    left: "Erin Marie San Valentin &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "Built on [Quart Academic Website Template](https://github.com/drganghe/quarto-academic-website-template) adapted from [Dr. Gang He](http://drganghe.github.io)"
    right:  
      - icon: github
        href: https://github.com/drganghe/quarto-academic-website-template
        target: _blank
      - text: "{{< fa brands bluesky >}}" 
        href: https://bsky.app
        target: _blank
      - icon: rss
        href: posts.xml
        target: _blank  
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://github.com/drganghe/quarto-academic-website-template
  
  open-graph: true
  
  twitter-card: true 
  
  site-url: "https://drganghe.github.io/quarto-academic-website-template"
  
  google-analytics:
    tracking-id: ""
    anonymize-ip: true 

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"